datacenter:
  children:
    routers:
      hosts:
        cisrt1003.blacklan.local: 
        #10.1.1.24[6:8]:
        #cisrt1001.kalivpn.pl:
        #10.0.0.7:
    #switches:
      #hosts: 
        #10.0.0.5:
        #10.1.1.250:
  vars:
    ansible_network_os: ios
    ansible_user: mszczechla
    ansible_password: Makofinal10
    ansible_connection: network_cli
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no-o HostKeyAlgorithms=ssh-rsa -o KexAlgorithms=diffie-hellman-group14-sha1'
