---
- name: Cisco show version example
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: show run
      ios_command:
        commands: show run | incl interface
      register: output

    - name: print output
      debug:
         var: output.stdout_lines
