---
- name: Cisco add loopback
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: configure interface settings
      cisco.ios.ios_config:
        lines: 
        - description test interface2
        - ip address 172.31.1.1 255.255.255.0
        parents: interface loopback13