---
- name: Cisco show version example
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: create a new user
      ios_user:
       name: ansible
       configured_password: ansible
       privilege: 15
       state: present




